name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install project dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Lint with Ruff
        run: |
          poetry run ruff check .

      - name: Run unit tests
        run: |
          poetry run pytest -q

      - name: Run integration tests
        run: |
          poetry run pytest --run-integration -q 